# Server
server:
  port: 30004
  tomcat:
    accept-count: 1000
# Spring native
spring:
  application:
    name: wnt-config
  datasource:
    url: jdbc:sqlserver://;serverName=10.0.14.40;databaseName=WebNTDB;trustServerCertificate=true
    username: WebNTDB
    password: 123456a@
    driver:
      class: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

  messages:
    basename: messages
    encoding: UTF-8
  jackson:
    time-zone: Asia/Ho_Chi_Minh
    date-format: dd/MM/yyyy HH:mm:ss

# Management
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}

# Logging
logging:
  file:
    path: /app/log
  logstash:
    host: localhost
    port: 5000

# security
security:
  username: ENC(Bq7G/JTejfXoJCk8nDp6iw==)
  password: ENC(r8wZZemi/0rdGJOBDoPlFw==)

org:
  springframework:
    boot:
      env:
        secretKey: giangnguye9699@2

# Eureka
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
    prefer-ip-address: true
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://ENC(Bq7G/JTejfXoJCk8nDp6iw==):ENC(M5yFp1/99ty4dXFasyeFBg==)@10.0.13.41:8001/eureka/